- docs/optimistic-rollup.md
https://github.com/nervosnetwork/godwoken/blob/update-withdraw-revert/docs/optimistic-rollup.md
> Update docs: withdrawal & reverting

- c/generator.c
- c/gw_def.h
- crates/generator/src/syscalls/mod.rs
- crates/generator/src/traits.rs
Create a godwoken account by a CKB `Script` and return the `account_id`.
> feat: Add create account syscall

- c/common.h
- c/generator.h
- c/gw_def.h
- crates/generator/Cargo.toml
- crates/generator/src/dummy_state.rs
- crates/generator/src/syscalls/mod.rs
- crates/generator/src/traits.rs
- crates/store/src/overlay.rs
- crates/store/src/store_impl.rs
* Add 2 syscalls:
- `SYS_LOAD_DATA`
- `SYS_STORE_DATA`
* Add 3 functions to gw_context_t
- `sys_load_nonce`
- `sys_load_data`
- `sys_store_data`
*
> feat: Handle account code in generator

- crates/chain/src/chain.rs
- crates/jsonrpc-types/src/genesis.rs
- crates/jsonrpc-types/src/parameter.rs
- crates/store/src/genesis.rs
- crates/store/src/store_impl.rs
- crates/types/src/core.rs
- packages/godwoken/index.d.ts
- packages/godwoken/native/src/lib.rs
- packages/tools/src/deploy_genesis.ts
This includes PR #21 together with JS side changes.
> fix sync interface

- c/contracts/sudt.c
- crates/chain/src/tests/deposition_withdrawal.rs
- crates/chain/src/tests/mod.rs
- crates/chain/src/tests/sync.rs
- crates/chain/src/tx_pool.rs
- crates/common/src/state.rs
- crates/generator/src/error.rs
- crates/generator/src/generator.rs
- crates/generator/src/traits.rs
- packages/godwoken/native/src/lib.rs
This PR fixes the withdrawal state in the Generator and add some unit tests.
But the complete withdrawal feature still need #15
> Fix withdrawal missing key error

- Cargo.lock
- crates/jsonrpc-types/src/godwoken.rs
- crates/store/src/overlay.rs
- crates/store/src/transaction.rs
- crates/traits/src/lib.rs
- packages/godwoken/index.d.ts
- packages/godwoken/lib/index.js
- packages/godwoken/native/Cargo.toml
- packages/godwoken/native/src/lib.rs
- packages/runner/src/jsonrpc_server.ts
* `gw_getTipBlockNumber`
* `gw_getBlockHashByNumber`
* `gw_getBlockByNumber`
* `gw_getBlock`
* `gw_getTransaction`
> Add more rpc methods

- crates/common/src/state.rs
- crates/generator/src/account_lock_manage/mod.rs
* Add more comments in common::state
* Only compile always_success in the debugging environments.
> Fix audit problems

- crates/block-producer/src/block_producer.rs
- crates/block-producer/src/produce_block.rs
- crates/chain/src/chain.rs
- crates/generator/src/genesis.rs
- crates/generator/src/tests/genesis.rs
- crates/mem-pool/src/pool.rs
- crates/rpc-server/Cargo.toml
- crates/rpc-server/src/lib.rs
- crates/rpc-server/src/registry.rs
- crates/rpc-server/src/server.rs
- crates/store/src/chain_view.rs
- crates/store/src/state_db.rs
- crates/store/src/store_impl.rs
- crates/store/src/tests/state_db.rs
- crates/store/src/transaction.rs
- crates/tests/src/testing_tool/chain.rs
- crates/tests/src/tests/deposition_withdrawal.rs
- crates/tests/src/tests/sync.rs
* Make StateDBTransaction sendable by remove RC.
* Remove public fields from Chain.
> Make StateDBTransaction sendable

- Cargo.lock
- Cargo.toml
- crates/block-producer/Cargo.toml
- crates/block-producer/src/main.rs
- crates/common/src/state.rs
- crates/config/src/config.rs
- crates/generator/src/account_lock_manage/mod.rs
- crates/generator/src/generator.rs
- crates/generator/src/syscalls/mod.rs
- crates/generator/src/traits.rs
- crates/generator/src/types.rs
- crates/jsonrpc-types/src/godwoken.rs
- crates/mem-pool/src/pool.rs
- crates/rpc-server/Cargo.toml
- crates/rpc-server/src/registry.rs
- crates/rpc-server/src/server.rs
- crates/tools/src/generate_config.rs
- crates/types/src/lib.rs
- crates/types/src/offchain.rs
> Add RPC server

- crates/block-producer/src/produce_block.rs
- crates/chain/src/chain.rs
- crates/generator/src/genesis.rs
- crates/mem-pool/src/pool.rs
- crates/rpc-server/src/registry.rs
- crates/store/src/state_db.rs
- crates/store/src/tests/state_db.rs
- crates/store/src/tests/transaction.rs
- crates/store/src/tests/transaction_clear_block_state.rs
- crates/store/src/transaction.rs
- crates/tests/src/tests/deposition_withdrawal.rs
- crates/tests/src/tests/sync.rs
* Fix user deposit caused inconsistent state.
* Fix clear block state.
* Add more assertions to check the account state.
> Fix clear block state

- crates/block-producer/src/block_producer.rs
- crates/block-producer/src/main.rs
- crates/block-producer/src/poller.rs
- crates/block-producer/src/produce_block.rs
- crates/block-producer/src/rpc_client.rs
- crates/chain/src/chain.rs
- crates/tests/src/tests/chain.rs
- crates/tests/src/tests/mod.rs
- crates/types/src/std_traits.rs
This error causes the inconsistent state between producing a layer2 block & syncing a layer2 block.
> Fix deposit request parsing

- crates/generator/src/syscalls/mod.rs
NOTE: this is a **BREAKING CHANGE**.
1. Fix `SYS_CREATE`,  `SYS_STORE_DATA`
2. Refactor the behavior of `SYS_LOAD_DATA`, `SYS_LOAD_ACCOUNT_SCRIPT` (use `store_data()`)
> Refactor syscall

- crates/block-producer/src/block_producer.rs
- crates/block-producer/src/lib.rs
- crates/block-producer/src/rpc_client.rs
- crates/block-producer/src/runner.rs
- crates/block-producer/src/transaction_skeleton.rs
- crates/block-producer/src/withdrawal.rs
- crates/chain/src/chain.rs
- crates/config/src/config.rs
- crates/tests/src/testing_tool/chain.rs
- crates/tools/src/deploy_genesis.rs
- crates/tools/src/generate_config.rs
Generate withdrawal cells
Revert withdrawal cells
> integrate withdrawal lock

- crates/block-producer/src/block_producer.rs
- crates/block-producer/src/produce_block.rs
- crates/block-producer/src/rpc_client.rs
- crates/block-producer/src/runner.rs
- crates/block-producer/src/wallet.rs
- crates/block-producer/src/withdrawal.rs
- crates/tests/src/testing_tool/chain.rs
- crates/tools/src/deploy_genesis.rs
* Fix the state-validator deployment
* Fix the rollup config cell deps
> Fix state validator

- crates/block-producer/src/utils.rs
Should try to generate change output cell if the owner cell included in inputs by poa already cover tx fee.
> fix(block producer): fill_tx_fee return if paid fee cover tx fee

- crates/block-producer/src/block_producer.rs
This also cause custodian cell not found
> fix(block producer): custodian lock args verification failure

- crates/benches/benches/benchmarks/sudt.rs
Add throughput display mode for TPS.
> Add throughput display mode for TPS.

- crates/web3-indexer/src/indexer.rs
> fix(web3-indexer): use as_bytes() to extract witness rollup action

- crates/block-producer/src/block_producer.rs
- crates/block-producer/src/produce_block.rs
- crates/block-producer/src/rpc_client.rs
- crates/block-producer/src/withdrawal.rs
- crates/chain/src/chain.rs
- crates/config/src/config.rs
- crates/generator/src/genesis.rs
- crates/store/src/transaction.rs
- crates/tests/src/testing_tool/chain.rs
- crates/tests/src/tests/deposition_withdrawal.rs
- crates/tools/src/generate_config.rs
Port https://github.com/nervosnetwork/godwoken/pull/183 to Master
> fix(block producer): withdrawal failure

- Cargo.lock
- crates/tools/Cargo.toml
- crates/tools/src/main.rs
- crates/tools/src/prepare_scripts.rs
The prepare-scripts command accept a config file, then prepare the scripts to deploy, and output scripts-deploy.json which can be used as input of deploy-scripts command.
The input config json file is like:
```json
{
"prebuild_image": "nervos/godwoken-prebuilds:v0.3.0",
"repos": {
"godwoken_scripts": "https://github.com/nervosnetwork/godwoken-scripts#v0.5.0-rc1",
"godwoken_polyjuice": "https://github.com/nervosnetwork/godwoken-polyjuice#v0.6.0-rc6",
"clerkb": "https://github.com/nervosnetwork/clerkb#v0.4.0"
},
"scripts": {
"challenge_lock": { "always_success": true },
"tron_account_lock": { "always_success": true },
"state_validator": { "always_success": true },
"l2_sudt_validator": { "always_success": true },
"meta_contract_validator": { "always_success": true },
"eth_account_lock": { …
```
> Impl gw-tools sub command: prepare-scripts

- crates/benches/benches/benchmarks/sudt.rs
- crates/common/src/error.rs
- crates/common/src/state.rs
- crates/generator/src/account_lock_manage/always_success.rs
- crates/generator/src/account_lock_manage/mod.rs
- crates/generator/src/account_lock_manage/secp256k1.rs
- crates/generator/src/generator.rs
- crates/generator/src/syscalls/mod.rs
- crates/generator/src/traits.rs
- crates/mem-pool/src/pool.rs
- crates/rpc-server/src/registry.rs
- crates/tests/src/tests/chain.rs
- crates/tests/src/tests/deposit_withdrawal.rs
- crates/types/schemas/godwoken.mol
- crates/types/src/conversion/blockchain.rs
- crates/types/src/generated/godwoken.rs
- crates/web3-indexer/src/indexer.rs
* Change SUDT key format
* Change `SYS_GET_BLOCK_HASH` syscall arguments order
* Fix `SYS_GET_SCRIPT_HASH_BY_PREFIX` syscall
* Add `SYS_RECOVER_ACCOUNT`  syscall
* Change `SUDTQuery`/`SUDTTransfer` data structure
> refactor: Interoperability

- docs/known_caveats_of_polyjuice.md
- docs/migrate_evm_contract_to_polyjuice.md
* Update known caveats of polyjuice 215dbae
* doc: Migrate EVM contract to polyjuice
> Add doc migrate evm contract to polyjuice

- crates/block-producer/src/block_producer.rs
- crates/block-producer/src/challenger.rs
- crates/block-producer/src/rpc_client.rs
- crates/block-producer/src/utils.rs
- dump tx and print cycles when block revert
- dump tx and print cycles when challenge cancel
- print cycles when submit l2 block under control of env var "GODWOKEN_DEBUG" (true or false)
> Add dump and get cycles

- crates/block-producer/src/challenger.rs
- crates/block-producer/src/poa.rs
- crates/block-producer/src/rpc_client.rs
Cancel challenge should filter inputs from verifier tx.
> fix(challenger): cancel challenge may spend owner cell twice

- crates/block-producer/src/block_producer.rs
- crates/block-producer/src/challenger.rs
- crates/block-producer/src/runner.rs
- crates/block-producer/src/utils.rs
- crates/config/src/config.rs
- crates/tools/src/deploy_genesis.rs
- crates/tools/src/generate_config.rs
* remove `debug_tx_dump_path` from `[config.block_producer]`
* Add a new structure `DebugConfig` on `[config.debug]`
> [BREAK CHANGE]Refactor config

- crates/chain/src/challenge.rs
- crates/generator/src/syscalls/mod.rs
- crates/types/src/offchain.rs
Save SYS_LOAD_ACCOUNT_SCRIPT script into RunResult, we can then
package these scripts into cancel challenge witness.
> fix: cancel polyjuice tx challenge failure

- crates/block-producer/src/produce_block.rs
- crates/block-producer/src/withdrawal.rs
Output the block producer verification erros for easy to debugging.
> chore: output tx & withdrawal verification errors

- crates/block-producer/src/block_producer.rs
- crates/generator/src/constants.rs
- crates/generator/src/generator.rs
- crates/generator/src/lib.rs
Limit min deposit capacity & withdrawal capacity to 1000 CKB.
We need to adjust this limitation to a minimal value in the further step.
> fix: limit min deposit capacity

- crates/block-producer/src/challenger.rs
- crates/block-producer/src/challenger/cancel_challenge.rs
- crates/block-producer/src/cleaner.rs
- crates/block-producer/src/debugger.rs
- crates/block-producer/src/rpc_client.rs
- crates/block-producer/src/runner.rs
- crates/chain/src/challenge.rs
- crates/generator/src/generator.rs
- crates/generator/src/syscalls/mod.rs
- crates/types/src/offchain.rs
Pass sys_load_data through cell_deps
> fix(challenger): cancel polyjuice tx call contract challenge failure v2

- Cargo.lock
- Cargo.toml
- crates/block-producer/Cargo.toml
- crates/block-producer/src/main.rs
- crates/version/Cargo.toml
- crates/version/build.rs
- crates/version/src/lib.rs
- crates/version/src/version.rs
> fix: output godwoken version in cli

- Cargo.lock
- crates/block-producer/src/runner.rs
- crates/chain/Cargo.toml
- crates/chain/src/chain.rs
- crates/challenge/src/offchain.rs
- crates/config/src/config.rs
- crates/jsonrpc-types/src/debugger.rs
- crates/jsonrpc-types/src/godwoken.rs
- crates/rpc-server/Cargo.toml
- crates/rpc-server/src/registry.rs
- crates/tests/src/testing_tool/chain.rs
- crates/tools/src/dump_tx.rs
- crates/tools/src/godwoken_rpc.rs
- crates/tools/src/main.rs
- feat(rpc): add ```debug_dump_cancel_challenge_tx``` method
- chore(config): add ```enable_debug_rpc``` to ```debug``` in ```config.toml```
- feat(tools): add ```dump-cancel-challenge-tx``` command to ```gw-tools```
> feat(rpc): debug dump cancel challenge tx

- crates/mem-pool/src/pool.rs
* Fix txs order when invert
* Add more logs on mem pool
> Fix txs order

- crates/block-producer/src/runner.rs
In the poll_loop function, we only output an error and continue the loop, this behavior causes some problems.
The scenario: on my local machine, I got a "disk is full" error when inserting new l2 block, the error poped up until the poll_loop function, and in poll_loop we log this error then continue to process the next l1 block, so then the node will never completes the syncing because we simply skipped a l2 block.
How to fix:
We simply exit the process in that scenario, the supervisor or docker will restart the godwoken process, then have a chance to recover from the error.
> fix: exit poll_loop function if we meet an error

- crates/chain/src/chain.rs
- crates/generator/src/error.rs
- crates/generator/src/generator.rs
We haven't check the checkpoint after execute a tx & withdrawal. This PR fix this.
> fix: verify checkpoint when apply block state

- crates/block-producer/src/produce_block.rs
- crates/challenge/src/context.rs
- crates/challenge/src/revert.rs
- crates/challenge/src/types.rs
- crates/types/schemas/godwoken.mol
- crates/types/src/generated/godwoken.rs
Relative godwoken script changes in [PR](https://github.com/nervosnetwork/godwoken-scripts/pull/80)
> [BREAKING CHANGE]: feat: check and track block timestamp in global state

- crates/db/src/schema.rs
- crates/mem-pool/src/constants.rs
- crates/mem-pool/src/mem_block.rs
- crates/mem-pool/src/pool.rs
- crates/rpc-server/src/registry.rs
- crates/store/src/transaction/mem_pool_store.rs
- crates/store/src/transaction/mod.rs
- crates/store/src/transaction/store_transaction.rs
- crates/tests/src/testing_tool/chain.rs
Store mem-pool txs, receipts, withdrawals into DB, thus we could reduce the unlock of mem-pool in RPC.
> feat: store mem-pool txs & withdrawals into DB

- crates/config/src/config.rs
- crates/rpc-client/src/indexer_client.rs
- crates/tools/src/account.rs
- crates/tools/src/address.rs
- crates/tools/src/create_creator_account.rs
- crates/tools/src/deploy_genesis.rs
- crates/tools/src/deploy_scripts.rs
- crates/tools/src/deposit_ckb.rs
- crates/tools/src/generate_config.rs
- crates/tools/src/main.rs
- crates/tools/src/polyjuice.rs
- crates/tools/src/prepare_scripts.rs
- crates/tools/src/setup.rs
- crates/tools/src/transfer.rs
- crates/tools/src/types.rs
- crates/tools/src/utils/cli_args.rs
- crates/tools/src/utils/transaction.rs
- crates/tools/src/withdraw.rs
- docs/quick-start.md
> Improve gw tool setup

- crates/config/src/config.rs
- crates/tools/src/deploy_scripts.rs
- crates/tools/src/main.rs
- crates/tools/src/setup.rs
- crates/tx-filter/src/polyjuice_contract_creator_allowlist.rs
- docs/quick-start.md
* Allowed list
* check allowed list if to_id is zero, since  user can create contract through meta contract
* change allowed list from id to eth address
* Tools
* Fix setup command on CKB mainnet.
> Change polyjuice contract allowed list from id to address

- Cargo.lock
- crates/block-producer/src/runner.rs
- crates/common/Cargo.toml
- crates/mem-pool/src/mem_block.rs
- crates/mem-pool/src/pool.rs
- crates/tests/src/testing_tool/chain.rs
- crates/types/Cargo.toml
1. Set block producer account to mem-pool
2. upgrade sparse-merkle-tree to v0.5.3
> Fix block producer

- crates/mem-pool/src/pool.rs
Collect  new deposits if mem pool account number is equals to new block account number.
> fix: optimize pending deposits strategy

- Cargo.lock
- crates/block-producer/src/runner.rs
- crates/mem-pool/src/pool.rs
- crates/mem-pool/src/withdrawal.rs
- crates/rpc-server/Cargo.toml
- crates/rpc-server/src/registry.rs
Check custodian cells in RPC and return error message
> Check custodian cells in rpc
