packages/runner/src/index.ts, packages/runner/src/jsonrpc_server.ts, packages/runner/src/runner.ts
This change provides a new readonly mode. Readonly mode is triggered
when aggregator private key is missing. Godwoken will then start a
server which only syncs changes, but make no L2 block submissions.
For now, submitL2Transaction/submitWithdrawalRequest are also
missing. Later when we integrate a proper transaction pool, those can
be enabled as well in readonly mode.
=> feat: Readonly mode

crates/block-producer/src/block_producer.rs, crates/mem-pool/src/pool.rs, crates/store/src/lib.rs, crates/store/src/snapshot.rs, crates/store/src/store_impl.rs
The SMT implementation can't support the previous design, so we choice a new way.
=> Update snapshot interface

Cargo.lock, crates/block-producer/Cargo.toml, crates/block-producer/src/lib.rs, crates/block-producer/src/main.rs, crates/block-producer/src/runner.rs
* The default behavior is compatible with the old version.
```
Godwoken 0.2.0-rc1
The layer2 rollup built upon Nervos CKB.
USAGE:
godwoken [SUBCOMMAND]
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
SUBCOMMANDS:
run                        Run Godwoken node
generate-example-config    Generate an example config file
help                       Prints this message or the help of the given subcommand(s)
```
=> Add simple cli options

Cargo.lock, crates/block-producer/src/runner.rs, crates/config/src/config.rs, crates/generator/src/genesis.rs, crates/generator/src/tests/genesis.rs, crates/tests/src/testing_tool/chain.rs, crates/tools/Cargo.toml, crates/tools/src/deploy_genesis.rs, crates/tools/src/generate_config.rs
Register secp256k1 data for `ecrecover` pre-compiled EVM contract to use.
NOTE: this PR add a config field (`secp_data_dep`) in `BlockProducerConfig`, which is a **BREAKING CHANGE** in config, and user should re-generate the `config.toml` config file.
=> Register secp256k1 data

Cargo.lock, crates/block-producer/Cargo.toml, crates/block-producer/src/runner.rs, crates/tools/src/generate_config.rs
* Enable persistent storage if `config.store.path` is not an empty path, otherwise we still using temporary storage.
* Update the `generate-config` command to generate an empty `config.store.path`. We should set the path to a directory after we fully tested the persistent storage feature.
=> Enable persistent storage

crates/db/src/schema.rs, crates/generator/src/dummy_state.rs, crates/generator/src/syscalls/mod.rs, crates/store/src/state_db.rs, crates/traits/src/lib.rs
* Add new syscall: get_script_hash_by_prefix, which allows us to search script_hash with a 20-bytes prefix string
* Adjust syscall error codes https://github.com/nervosnetwork/godwoken/pull/195/files#diff-16f67f4822618c8e4616f5d07b43084312bdba514bf01f1c696cd16a86a6d496R54
* Change the behavior of syscall `SYS_LOAD_ACCOUNT_ID_BY_SCRIPT_HASH` & `SYS_LOAD_DATA`, return error code if not found instead of terminating the execution.
=> Add syscall: get script hash by prefix

crates/block-producer/src/produce_block.rs, crates/chain/src/chain.rs, crates/db/src/schema.rs, crates/generator/src/generator.rs, crates/generator/src/genesis.rs, crates/generator/src/tests/genesis.rs, crates/generator/src/traits.rs, crates/mem-pool/src/pool.rs, crates/rpc-server/src/registry.rs, crates/store/src/state_db.rs, crates/store/src/tests/state_db.rs, crates/store/src/tests/transaction_clear_block_state.rs, crates/store/src/transaction.rs, crates/tests/src/tests/chain.rs, crates/tests/src/tests/deposition_withdrawal.rs, crates/types/schemas/store.mol, crates/types/src/generated/store.rs, crates/web3-indexer/src/indexer.rs
Add ```CheckPoint```, ```SubState``` and ```StateDBMode```
Save every withdrawal and transaction post state to db
Able to load statedb from checkpoint(block_number with ```SubState```) and ```StateDBMode```
=> feat(statedb): support loading from checkpoint state

crates/mem-pool/src/pool.rs
Workaround:
When push new l2 tx into mempool, also remove withdrawal with
lower or equal nonce.
=> fix(blockproducer): invalid withdrawal request block l2 tx

crates/tools/src/generate_config.rs, crates/tools/src/main.rs, crates/tools/src/setup_nodes.rs
Update OPTIONS( delete one and add new three):	
...
~~-p  \<polyjuice-binaries-dir-path\>   Polyjuice binaries directory path~~	
-k  \<privkey-path\>			            The private key file path
-c  \<scripts-deploy-config-path\> 	    Scripts depoly config json file path
-u  \<rpc-server-url\>				    Rpc server url [default: localhost:8119]
The original command line is as follows:
```bash
cargo run --bin gw-tools -- generate-config -g deploy/genesis-deploy-result.json -s deploy/scripts-deploy-result.json  
-o config.toml -p deploy/
```
The updated command line is as follows:
```bash
cargo run --bin gw-tools -- generate-config -g deploy/genesis-deploy-result.json -s deploy/scripts-deploy-result.json  
-o deploy/node1/config.toml -k deploy/node1/pk -c deploy/scripts-deploy.json 
```
All fields …
=> Update generate-config command

crates/block-producer/src/produce_block.rs, crates/generator/Cargo.toml, crates/generator/src/generator.rs, crates/generator/src/syscalls/mod.rs, crates/generator/src/traits.rs, crates/traits/src/lib.rs, crates/types/schemas/godwoken.mol, crates/types/src/generated/godwoken.rs, crates/web3-indexer/src/indexer.rs
This PR aims to adjust structures & syscalls to make it possible to charge fees in built-in scripts & in the withdrawal.
Changes:
1. Update the godwoken.mol file, add `fee` fields to built-in scripts arguments.
2. Add the logic to charge the fee for withdrawal.
3. Adjust syscall numbers.
4. Add a new syscall SYS_PAY_FEE to record the fee paid to the block producer.
=> Support charge tx fee in built-in scripts & withdrawal

crates/tools/src/main.rs, crates/tools/src/prepare_scripts.rs, crates/tools/src/setup.rs, crates/tools/src/setup_nodes.rs
This command can do all the tasks such as preparing scripts, deploying scripts, setting nodes, deploying genesis and generating configs, with one line of command， the call is as follows:
```bash
RUST_LOG=info cargo +nightly run --bin gw-tools -- setup -s deploy/scripts-build.json -k deploy/pk -o deploy/
```
The input file scripts-build.json of this command is the same as the input file of prepare-scripts:
```json
{
"prebuild_image": "nervos/godwoken-prebuilds:v0.3.1",
"repos": {
"godwoken_scripts": "https://github.com/nervosnetwork/godwoken-scripts#v0.6.0-rc1",
"godwoken_polyjuice": "https://github.com/nervosnetwork/godwoken-polyjuice#v0.6.0-rc6",
"clerkb": "https://github.com/nervosnetwork/clerkb#v0.4.0"
},
"scripts": {
"challenge_lock": { "always_success": true },
"tron_account_lock": { …
```
=> impl gw-tools-setup

Cargo.lock, crates/block-producer/Cargo.toml, crates/block-producer/src/main.rs, crates/block-producer/src/rpc_client.rs, crates/block-producer/src/runner.rs, crates/tools/src/deploy_genesis.rs, crates/tools/src/main.rs, crates/tools/src/setup.rs
- rollup-config.json：burn_lock_hash must be 0x0000..00
- poa-config.json: round_intervals > 0
If skip the check can use --skip-config-check flag：
```bash
cargo run --bin gw-tools -- deploy-genesis -k deploy/pk -d deploy/scripts-deploy-result.json -p deploy/poa-config.json  
-u deploy/rollup-config.json -o deploy/genesis-deploy-result.json --skip-config-check
``` 
- ckb version > 0.40.0
- all eoa type hashes in the rollup config cell are registered in godwoken
- all contract type hashes in the rollup config cell are registered in godwoken
If skip the check can use --skip-config-check flag：
```bash
RUST_LOG=info cargo +nightly run --bin godwoken run -c deploy/node1/config.toml --skip-config-check
```
=> check config when deploy genesis and godwoken node run

crates/block-producer/src/runner.rs, crates/block-producer/src/test_mode_control.rs, crates/config/src/config.rs, crates/rpc-server/src/registry.rs, crates/tools/src/generate_config.rs
When ReadOnly:
- node will not produce blocks.
- node block_producer configuration can be filled in blanks
- skip check check_rollup_config_cell
=> Add readonly mode

crates/generator/src/syscalls/mod.rs
The syscall should return error to user if the internal state is correct.
=> fix syscalls: SYS_LOAD_ACCOUNT_SCRIPT return not found if script_hash is zero

crates/block-producer/src/block_producer.rs, crates/block-producer/src/debugger.rs, crates/block-producer/src/lib.rs, crates/block-producer/src/rpc_client.rs, crates/config/src/config.rs, crates/jsonrpc-types/src/debugger.rs, crates/jsonrpc-types/src/lib.rs, crates/tools/src/generate_config.rs
A new config field added to the BlockProducerConfig: `debug_tx_dump_path`
=> [BREAK CHANGES]Dumping txs when failed to submit a block

crates/generator/src/syscalls/error_codes.rs, crates/generator/src/syscalls/mod.rs
1. Rename `FATAL_ACCOUNT_NOT_FOUND` 63 to `GW_FATAL_SCRIPT_NOT_FOUND`
2. Add `GW_ERROR_ACCOUNT_NOT_FOUND` 85
3. Return `GW_ERROR_ACCOUNT_NOT_FOUND` in syscalls if account isn't exist.
4. Return FATAL if recover account with a unknown code_hash
=> Update error codes

crates/block-producer/src/block_producer.rs, crates/block-producer/src/produce_block.rs, crates/chain/src/chain.rs, crates/generator/src/generator.rs, crates/generator/src/lib.rs, crates/generator/src/vm_cost_model.rs, crates/tests/src/testing_tool/chain.rs, crates/types/src/offchain.rs
1. Introduce VM cycles model.
2. Limit a single l2 tx to 5000_0000 cycles. based on our previous test case, the maximum cycles is ~4900_0000, so I choose a value higher than this.
3. Output offchain cycles of a layer2 block.
=> Set l2tx max cycles

crates/store/src/transaction.rs, crates/tests/src/testing_tool/chain.rs, crates/tests/src/tests/deposit_withdrawal.rs
The deposited assets should be calculated after block finalized. But the withdrawal assets should be calculated immediately.
This bug causes Godwoken node failed to check the available assets, and trying to collect custodian cells we actually do not have, thus, this causes the rollup stop produce new blocks.
=> fix: fix the calculation of finalized assets

Cargo.lock, crates/block-producer/src/block_producer.rs, crates/block-producer/src/rpc_client.rs, crates/block-producer/src/withdrawal.rs, crates/mem-pool/Cargo.toml, crates/mem-pool/src/pool.rs
If only one or two finalized custodian cells are in the rollup, Godwoken may fail to generate the withdrawal cells. The reason is that cells need a specific capacity to keep themselves on-chain, so if a user wants to withdraw from the rollup, the remained capacity may not be enough for a refunded cell. 
Since the mechanism of mem pool, Godwoken will continually retry this process and failed to produce a new block.
This PR applied a temporary fix: when we failed to generate withdrawal cells, we randomly reject withdrawals from the mem pool. Thus, when this bug occurred, the rollup still can provide service except for withdrawal. 
This affects limited users since it only occurred when there are very few finalized cells in the rollup.
In the future, we will refactor the mem pool and provide …
=> fix: try to recover error when failed to generate withdrawal cells

crates/block-producer/src/runner.rs, crates/config/src/config.rs, crates/tools/src/generate_config.rs, crates/web3-indexer/src/indexer.rs
make web3-indexer collect the transaction with tron_account_lock as well as eth_account_lock, thus the web3 rpc can support tron account related transaction receipt.
=> fix(web3-indexer): collect tron transaction to support getTransactionReceipt for tron

crates/block-producer/src/block_producer.rs, crates/mem-pool/src/mem_block.rs, crates/mem-pool/src/pool.rs
* Prevent duplicated state keys in the witness
* Try to recovery from invalid state by empty the mem-pool(a temporary fix)
=> Hotfix v0.6.2 rc6

crates/block-producer/src/runner.rs, crates/config/src/config.rs
* Remove enable from OffchainValidatorConfig
* Turn off OffchainValidator by default. (We will enable it again afterwe successfully validate all testnet txs)
* set dump failed txs to true.
=> chore: turn off offchain-validator on default

Cargo.lock, crates/block-producer/Cargo.toml, crates/block-producer/src/db_block_validator.rs, crates/block-producer/src/history_validator.rs, crates/block-producer/src/lib.rs, crates/block-producer/src/main.rs, crates/block-producer/src/runner.rs, crates/challenge/src/cancel_challenge.rs, crates/challenge/src/context.rs, crates/challenge/src/offchain.rs, crates/challenge/src/offchain/verify_tx.rs, crates/common/src/merkle_utils.rs, crates/config/src/config.rs, crates/jsonrpc-types/src/godwoken.rs, crates/tools/src/generate_config.rs
- feat:  new ```verify-db-block [-c config] [-f from-block] [-t to-block]``` command
- feat: support replace code hash binary, only support type
for example:
```
[db_block_validator.replace_scripts]
0xd6d4b52ed2882cb0b2e1f802817c0ab05bd27da89a41ceddb25e0e347689ce69 = '../godwoken-scripts/c/build/meta-contract-validator'
0xb6d6a2882d3d08cea565047bfe901cb2afe0cb790ea5e1b61e0532ef237c4a02 = '../godwoken-scripts/c/build/sudt-validator'
0xbeb77e49c6506182ec0c02546aee9908aafc1561ec13beb488d14184c6cd1b79 = '../godwoken-polyjuice/build/validator'
0xb761c2e77a9f7090ccb9d864ca6136e883257498230fb096ccbfd56e30c142f4 = '../godwoken-scripts/build/release/challenge-lock'
```
- feat: support skips block and target
for example:
```
[db_block_validator]
skip_targets = [
[35195, 'tx_execution', 0],
[35198, …
```
=> feat(command): db block validator

crates/benches/benches/benchmarks/sudt.rs, crates/block-producer/src/runner.rs, crates/config/src/config.rs, crates/generator/src/account_whitelist.rs, crates/generator/src/erc20_creator_whitelist.rs, crates/generator/src/error.rs, crates/generator/src/generator.rs, crates/generator/src/lib.rs, crates/tests/src/testing_tool/chain.rs, crates/tools/src/generate_config.rs
```toml
[rpc]
allowed_sudt_proxy_creator_account_id = [1] ## only account_id = 1 can create sudt proxy contract
sudt_proxy_code_hashes = ["0x43a008ec973b648bd71ad67e6b66f2be8a6fa88e89c7dad046c948b00aa866aa"] ## supported sudt proxy contract code hashes
```
=> feat: validate sudt proxy contract creator by adding whitelist in [rpc] config

crates/block-producer/src/stake.rs, crates/rpc-client/src/rpc_client.rs
If there are multiple stake cells we would blindly choose the frist returned cell. But the cell's capacity may not enough for the rollup staking, this causes the block producer failed to submit a block.
=> fix: search stake cell with minimum capacity

Cargo.lock, crates/block-producer/src/runner.rs, crates/jsonrpc-types/src/godwoken.rs, crates/mem-pool/src/pool.rs, crates/mem-pool/src/traits.rs, crates/rpc-server/src/registry.rs, crates/tests/src/testing_tool/chain.rs, crates/types/src/offchain/error_receipt.rs, crates/types/src/offchain/mod.rs, crates/web3-indexer/Cargo.toml, crates/web3-indexer/migrations/20211015154325_create_error_transactions.sql, crates/web3-indexer/src/error_receipt_indexer.rs, crates/web3-indexer/src/lib.rs
- for ```execute_l2transaction``` and ```execute_raw_l2transaction```, response error receipt in jsonrpc error data field
- for ```submit_l2transaction```, save error receipt to web3 indexer database and clear them after expiration blocks
=> feat(rpc): error tx receipt

crates/block-producer/src/block_producer.rs, crates/block-producer/src/poller.rs, crates/block-producer/src/utils.rs, crates/chain/src/chain.rs, crates/generator/src/genesis.rs, crates/mem-pool/src/pool.rs, crates/store/src/transaction/store_transaction.rs
Submit local produced block to chain instantly, this behavior should reduce the number of re-run txs in mem-pool.
=> Support submit local block

crates/block-producer/src/block_producer.rs, crates/block-producer/src/poller.rs, crates/chain/src/chain.rs, crates/challenge/src/offchain/mock_poa.rs, crates/mem-pool/src/default_provider.rs, crates/mem-pool/src/pool.rs, crates/mem-pool/src/traits.rs, crates/poa/src/poa.rs, crates/tests/src/testing_tool/mem_pool_provider.rs, crates/tests/src/tests/chain.rs, crates/tests/src/tests/deposit_withdrawal.rs
1. prevent produce new block if current tip is a pending block(not committed to a layer1 block yet).
2. skip duplicated mem-pool reset.
3. fix block timestamp introduced by 2
=> Fix fast path sync

Cargo.lock, crates/mem-pool/Cargo.toml, crates/mem-pool/src/deposit.rs, crates/tests/src/testing_tool/chain.rs, crates/tests/src/tests/chain.rs, crates/tools/src/deposit_ckb.rs, crates/utils/src/lib.rs, crates/utils/src/since.rs
Deposit lock can be unlock by user after `cancel_timeout` if the cell is not get packaged by sequencer.
To prevent conflict with user's unlock, we check and filter deposit cell's by `cancel_timeout`, only package cells with required `cancel_timeout`.
The current `cancel_timeout` fields must be relative time flag. We support three types of the time lock:
* if user set `cancel_timeout` to block numbers, the required number is 150 blocks.(~ 20 minutes)
* if user set `cancel_timeout` to timestamp, the required timestamp is 1200s. (20 minutes)
* if user set `cancel_timeout` to epoch, the required epoch is 1 epoch. (~ 4 hours, we recommended to use the first two)
See [tx since rfc](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0017-tx-valid-since/0017-tx-valid-since.md) for details.
=> feat: check and filter deposit cells by cancel timeout

Cargo.lock, crates/rpc-client/src/indexer_client.rs, crates/tools/Cargo.toml, crates/tools/src/main.rs, crates/tools/src/stat/mod.rs
Example, query mainnet custodian CKB:
gw-tools stat-custodian-ckb --rollup-type-hash 0x40d73f0d3c561fcaae330eabc030d8d96a9d0af36d0c5114883658a350cb9e3b --custodian-script-type-hash 0x45c112df97daece27c4afa02b24b15f64403bdfd45ab2e0e88c9fb2a24796b1d --ckb-indexer-rpc https://mainnet.ckbapp.dev/indexer
=> feat: support query amount of layer2 custodian CKB in gw-tools

Cargo.lock, crates/benches/benches/benchmarks/smt.rs, crates/benches/benches/benchmarks/sudt.rs, crates/common/src/error.rs, crates/config/Cargo.toml, crates/config/src/config.rs, crates/generator/src/backend_manage.rs, crates/generator/src/generator.rs, crates/jsonrpc-types/src/godwoken.rs, crates/rpc-server/Cargo.toml, crates/rpc-server/src/registry.rs, crates/tests/src/testing_tool/chain.rs, crates/tools/src/generate_config.rs, crates/tools/src/get_balance.rs, crates/tools/src/main.rs, crates/tools/src/update_cell.rs, crates/tools/src/withdraw.rs, crates/utils/Cargo.toml, crates/utils/src/fee.rs
1. check if the fee or fee_rate/gasPrice of the L2Transaction is enough
- check the fee of MetaContract::CreateAccount
- check the fee of SUDTTransfer
- check the gasPrice of Polyjuice L2TX
gasPrice: Value of the gas for a transaction
return： if the fee is too low for acceptance, return  RpcError, such as:
`{"jsonrpc":"2.0","id":57,"error":{"code":-32602,"message":"Gas Price too low for acceptance, should more than polyjuice_minimum_gas_price(500 shannons)."}}',
error: Error: Gas Price too low for acceptance, should more than polyjuice_minimum_gas_price(500 shannons).`
2. check the fee of WithdrawalRequest
The default `fee_rates` HashMap is empty, which means that `check_fee` will always be successful.
```toml
[mem_pool.fee_config]
meta_contract_fee_weight = 2
sudt_transfer_fee_weight = 2 …
```
=> feat(RPC): check if the fee or gasPrice is enough

Cargo.lock, crates/block-producer/src/block_producer.rs, crates/block-producer/src/debugger.rs, crates/block-producer/src/runner.rs, crates/challenge/src/offchain.rs, crates/mem-pool/Cargo.toml, crates/mem-pool/src/default_provider.rs, crates/mem-pool/src/deposit.rs, crates/mem-pool/src/pool.rs, crates/mem-pool/src/traits.rs, crates/rpc-client/src/rpc_client.rs, crates/tests/src/testing_tool/chain.rs, crates/tests/src/testing_tool/mem_pool_provider.rs, crates/tests/src/tests/chain.rs, crates/tools/src/deposit_ckb.rs, crates/types/src/offchain/rpc.rs, crates/types/src/std_traits.rs, crates/utils/src/lib.rs, crates/utils/src/since.rs
This PR fixes the potential inconsistent state during mem-pool reset.
Some users report they found txs revert after get the tx receipt.
The mem-pool reset it's state when receive new l2block, then calculate new state of the next block:
1. execute l2 withdrawals
2. execute l2 deposits
3. execute l2 txs
Unlike withdrawals & txs, the deposits is collected from layer1 CKB's cells, and the count of collected deposits is uncertain everytime.
This 'uncertain' causes the problem, every time we reset the mem-pool the deposits cells may changed, and new created accounts are changed, for example:
The first time mem-pool reset creates 3 accounts:
1. Deposit A(id: 100)
2. Deposit B(id: 101)
3. Contract Account(id: 102)
But when the mem-pool resets again, the accounts are changed:
1. Deposit A(id: 100) …
=> Fix revert txs and inconsistent state

docs/rocksdb_tuning.md
1. Remove the block size, use default value(4K). Tuning this value do not affect the performance of our program.
2. Increase `write_buffer_size` to 64M, in stress testing we see the error:
```
Transaction could not check for conflicts for operation at SequenceNumber 11871223343 as the MemTable only contains changes newer than SequenceNumber 11871336085.  Increasing the value of the max_write_buffer_size_to_maintain option could reduce the frequency of this error.
```
The `max_write_buffer_size_to_maintain ` is setting to -1, so RocksDB will tuning max write buffer to `write_buffer_size * max_write_buffer_number`.
We increase the write_buffer_size to avoid the error.
=> doc: update rocksDB tuning
